global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['people:8080', 'movies:8080']
  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:8001']
  - job_name: 'jaeger'
    metrics_path: /metrics
    static_configs:
      - targets: ['jaeger:14269']
