global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'services'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['people-api:8080', 'movies-api:8080', 'cinematography-api:8080']
  - job_name: pushgateway
    honor_labels: true
    metrics_path: /metrics
    static_configs:
    - targets: ['pushgateway:9091']
  - job_name: 'databases (mongodb)'
    scrape_timeout: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['mongodb-people-exporter:9216', 'mongodb-movies-exporter:9216']
  - job_name: 'databases (neo4j)'
    metrics_path: /metrics
    static_configs:
      - targets: ['cinematography-db:2004']
  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:8001']
  - job_name: 'kafka'
    scrape_timeout: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['kafka:7071', 'kafka:7072']
  - job_name: 'jaeger'
    metrics_path: /metrics
    static_configs:
      - targets: ['jaeger:14269']
